### ISSUE TITLE
adding the css file to the lib and dist directories

### ISSUE THREAD

**Issue by vakopian** [LKay/react-bootstrap-datetimepicker#1]
Since `eonasdan-bootstrap-datetimepicker` is only a dev dependency for this module, wouldn't it be better if the build script adds the css file in the lib and dist directories so that the programs who use this module don't have to add a dependency to `eonasdan-bootstrap-datetimepicker`?
If you agree, I can make a pull request.

BTW, I love how much you have improved the original module!

**Comment by LKay** [comment]
I didn't want to add it other way and copy the styles to the dist directory that way. It's a 3rd party plugin and the react version of the module just utilises the same CSS styles without any modifications. If I were to copy the files during the build it will be redundant step and to my mind the styles should be copied/compiled in (if using less/sass etc.) independently. 

I could add a submodule to the repo pointing to `eonasdan-bootstrap-datetimepicker` but as git doesn't support linking to a single file I'd rather leave it as it its to not add bunch of unnecessary files to the repo.

I'm open to discussion about that.

**Comment by vakopian** [comment]
Then perhaps `eonasdan-bootstrap-datetimepicker` should be moved into `dependencies`?

**Comment by vakopian** [comment]
I just checked how react-bootstrap handles the same issue - they have the same problem, `react-bootstrap` uses bootstrap css but not js. And it seems like they are doing what you are doing: `bootstrap` is only a dev dependency. Closing this issue
