### ISSUE TITLE
npm package name conflict?

### ISSUE THREAD

**Issue by crobinson42** [LKay/react-bootstrap-datetimepicker#5]
This appears to be a duplicate of another `react-bootstrap-datetimepicker` https://github.com/quri/react-bootstrap-datetimepicker/

Both give instructions for `npm install react-bootstrap-datetimepicker`... that's very confusing.

Can you shed some light on this?! I was searching for a better bootstrap datetime picker because https://github.com/quri/react-bootstrap-datetimepicker/ is horribly maintained. It appears you're a little more current and active in your library, what's the status and comparison between the two?

**Comment by LKay** [comment]
This repo is a complete rewrite of the other one you mentioned. I'm adding features on my free time and right now it has much more features than the other one. I'm still keeping the references to the other npm package as I hope to eventually merge my repo into the original one. If not then I'll just name it differently and push it to npm.

For now you can use my package  by adding `"react-bootstrap-datetimepicker" : "lkay/react-bootstrap-datetimepicker"` to your `package.json` which will fetch the current `master` branch code for you.

For docs and available options you can look at original package or the original plugin http://eonasdan.github.io/bootstrap-datetimepicker/Options and source code as I haven't made any actual docs yet.

**Comment by crobinson42** [comment]
Thanks for the response!
